image: Ubuntu 1804 #образдлясборки
stack: node10 #окружение 
branches: 
  only: 
    -master #веткa git 
cache: node_modules #кеширование
install: 
  -npm install #команда установки зависимостей 
build: off 
build_script: 
  -yarn run build #команда сборки 
test_script: 
  -npm run lint && npm test #скрипт тестирования 
deploy_script: #скрипт развёртывания
  -gitconfig --global credential.helper store
  -gitconfig --global user.nameAppVeyor
  -gitconfig --globaluser.emailci@appveyor.com
  -echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com">"$HOME/.git-credentials"
  -npx push-dir --dir=dist --branch=gh-pages --force --verbose